### PR TITLE
Update README.md about installation from AUR

### PR DESCRIPTION
**Pull request by orhun**
Hey,
I'm an [Arch Linux](https://aur.archlinux.org) package [maintainer](https://github.com/orhun/PKGBUILDs). I'm submitting this PR to let you know that I created the following packages for the installation of `cicero` on Arch Linux and other distributions that support installing packages from [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository):

* [cicero](https://aur.archlinux.org/packages/cicero/) (builds from source)
* [cicero-git](https://aur.archlinux.org/packages/cicero-git/) (VCS/development package)

PS: I can create a `-bin` package if you provide a pre-compiled x86_64 binary along with the release artifacts.

I also updated README.md about installation from AUR. (ddaa04d)

BR,
orhun.

### CODE REVIEW

**Comment by eyeplum** [comment]
Thank you for creating the AUR packages and updating the README.md!

I will look into adding a pre-compiled binary in release artifacts for future releases :)

**Comment by orhun** [comment]
Hey again!

`cicero` can't be built with the cargo `--locked` flag which affects the [reproducibility](https://wiki.archlinux.org/index.php/Reproducible_Builds) of the package.

```
error: Cargo.lock needs to be updated but --locked was passed to prevent this
```

So do you mind updating the `Cargo.lock` file? (with running `cargo build`)

Thank you,
orhun.

**Comment by eyeplum** [comment]
Hey @orhun ,

Apologies! I think when I modified `Cargo.toml` for `v0.1.2` I didn't run `cargo build`.

I was planning to add a small feature (handling PageUp/PageDown keys in the grapheme list), so I've now:
- Implemented the feature
- Released `v0.1.3` and updated `Cargo.lock`
- Added `--locked` to the CI build

Would you be able to try again with `v0.1.3`?

Thanks!

**Comment by orhun** [comment]
Everything seems good now, thank you for your attention. 👍🏼

**Pull request merged**
